In [22]:
import torch

input_ids = torch.tensor([2, 3, 5, 1])

print(input_ids)

tensor([2, 3, 5, 1])


- Để đơn giản hóa, giả sử chúng ta có 1 *vocabulary* nhỏ gồm `6 từ` (thay vì 50,257 từ trong *vocabulary* của BPE), và chúng ta muốn tạo *embedding* có `kích thước 3` (trong GPT-3 embedding có 12,288 chiều).

In [ ]:
vocab_size = 6  # Kích thước vocabulary
embedding_dim = 3  # Kích thước embedding

torch.manual_seed(123)  # Đặt seed để kết quả không đổi khi chạy lại nhiều lần

embedding_layer = torch.nn.Embedding(vocab_size, embedding_dim)

print(embedding_layer.weight)

Parameter containing:
tensor([[-1.3316,  0.2230, -0.1207],
        [-0.9797, -2.1126, -0.2721],
        [-0.3510,  1.1152, -0.6172],
        [-2.2708, -0.1086,  1.1721],
        [-0.4372, -0.4053,  0.7086],
        [ 0.9533, -0.0130, -0.1301]], requires_grad=True)


- Ở ma trận trên, mỗi hàng tương ứng với 1 trong 6 token trong *vocabulary*, mỗi cột tương ứng với 1 trong 3 chiều *embedding*.

In [20]:
print(embedding_layer(torch.tensor([2])))

tensor([[-0.3510,  1.1152, -0.6172]], grad_fn=<EmbeddingBackward0>)


- Có thể thấy với `token 2` này tương ứng với element thứ 3 trong embedding weights.

- Nói cách khác, `embedding layer` thực chất chỉ là 1 phép tra cứu (`look-up operation`). 